### ISSUE TITLE
Seqeval methods require list of list

### ISSUE THREAD

**Issue by papi656** [dmis-lab/bioner-generalization#1]
The code in present form is not working. The methods from seqeval requires parameters to be list of list. 
For example this line of code (evaluate.py, line 225) `p = precision_score(test_splits['Overall'], predictions)` should be replaced with `p = precision_score([test_splits['Overall']], [predictions])`
This change worked for me.

**Comment by nowkim** [comment]
@papi656 Thank you for raising this issue! I'll check the code and correct the error within a few days. Thanks again!

**Comment by nowkim** [comment]
I've updated the code.
